#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 31 15:01:08 2017

@author: wangbeanz
"""

import threading
import time

def thread_job():
    print('T1 start\n')
    for i in range(10):
        time.sleep(0.1)
    print('T1 finish\n')

def T2_job():
    print('T2 start\n')
    print('T2 finish\n')

def main():
    added_thread = threading.Thread(target=thread_job, name='T1')  # add a new thread.
    thread2 = threading.Thread(target=T2_job, name='T2')
    added_thread.start()  # start the thread.
    thread2.start()
    added_thread.join()
    thread2.join()
    print('all done.')
    # print(threading.active_count())  # counting the numbers of activate threads.
    # print(threading.enumerate())
    # print(threading.current_thread())

if __name__=='__main__':
    main()