#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  3 22:33:38 2017

@author: wangbeanz
"""

import cv2
import numpy as np

img = cv2.imread('cat.jpg', cv2.IMREAD_COLOR)


# change to white
# img[55, 55] = [255, 255, 255]
px = img[55, 55]
# print out color pixel
print(px)

# region of image
ROI = img[100:150, 100: 150]
print(ROI)  # print out the color pixel

img[100:150, 100:150] = [255, 255, 255]

cat_face = img[40:114, 287:374]
img[0:74, 0:87] = cat_face


cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

