#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  1 16:55:21 2017

@author: wangbeanz
"""
# This is a opencv tutorial of sentdex.
# https://www.youtube.com/watch?v=Z78zbnLlPUA

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('cat.jpg', cv2.IMREAD_GRAYSCALE)
# IMREAD_COLOR = 1
# IMREAD_UNCHANGED = -1

cv2.imshow('img cat', img)
cv2.waitKey(0)  # press any key to destroy the windows.
cv2.destroyAllWindows()
cv2.imwrite('cat_gray.jpg', img)

plt.imshow(img, cmap='gray', interpolation='bicubic')
plt.show()