#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 29 20:10:47 2017

@author: wangbeanz
"""

import numpy as np

# 1 * 5 matrix, you can think as one sample.
a = np.random.randn(5)
expa = np.exp(a)  # exponentiate
answer = expa / expa.sum()

# check to see if the sum of the answer is equal to 1.
print(answer.sum())

# 100 * 5 matrix, 100 samples and 5 features.
A = np.random.randn(100, 5)
expA = np.exp(A)

# keep the rows equals to 1.
answer = expA / expA.sum(axis=1, keepdims=True)
print(answer.sum(axis=1))  # answeer, (100, )
print(expA.sum(axis=1, keepdims=True))  # denominator, (100, 1)
print(expA)  # (100, 5)